### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by tobigit** [monospaced/angular-elastic#33]
Our customers see performance lags when typing very fast.
I debugged the elastic code and saw that every key stroke fires the adjust-function 2 times! One time called by the model-watcher and second time by the "oninput"-event of the textarea.

To improve the performance I buffered the function-call of adjust:

``` js
var bufferedAdjust = null;
function adjust() {
    if( !bufferedAdjust ) {
      bufferedAdjust = $timeout(_adjust, 100);
      bufferedAdjust.then(function () {
        bufferedAdjust = null
      });
    }
}

function _adjust() {
 // here is the original adjust-function-code
...
```

**Comment by monospaced** [comment]
to investigate

**Comment by prasad83** [comment]
Any updates on this please?

**Comment by Zenkit** [comment]
We also experience performance issues when the user enters a lot of text and then types fast. The profiler points out that the adjust function takes long because of "getPropertyValue" which I suppose means reading styles values from the DOM. Is there a way to bypass that?

<img width="501" alt="bildschirmfoto 2016-06-14 um 09 42 46" src="https://cloud.githubusercontent.com/assets/13518649/16034919/9ea00c36-3214-11e6-8c0f-ce20007a74d8.png">

**Comment by monospaced** [comment]
Archiving repository.
