### ISSUE TITLE
ng-attr-msd-elastic="{{undefined}}" should not autosize

### ISSUE THREAD

**Issue by KrzysztofKarol** [monospaced/angular-elastic#91]
I want to conditionally autosize textarea.
And for `ng-attr-msd-elastic="{{undefined}}"` `msd-elastic` is not showing up in element but element is autosized.

http://jsfiddle.net/78tycgke/2/

I tested also with classes:
http://jsfiddle.net/78tycgke/3/

I guess timing is the problem.

**Comment by joaopgg** [comment]
Yep, same problem here

**Comment by Dexmaster** [comment]
fixed in fork https://github.com/Dexmaster/angular-elastic, I can create PR if someone wishes to merge it, but in last 2 years no changes were done, so I believe there is no chance of it being merged. 

can be used as `npm i git://github.com/Dexmaster/angular-elastic.git#v2.5.2`
here is example: http://jsfiddle.net/78tycgke/7/

**Comment by monospaced** [comment]
This is the expected behaviour in AngularJS, `ng-attr` can't be use to prevent directive from compiling see https://github.com/angular/angular.js/issues/14575
