### ISSUE TITLE
Takes a lot of time to load with lots of data

### ISSUE THREAD

**Issue by hazz1925** [monospaced/angular-elastic#96]
Hi, I am having a problem when using elastic in ng-repeat. It is taking awful a lot of time to load for 5000 data (ng-repeat). Without elastic it only took around 20 seconds but with elastic it took around 1 hour and it will also go unresponsive. 

Did anyone experience the same problem?

**Comment by monospaced** [comment]
I'm not surprised that this does not work well in a 5000 long `ng-repeat`.

For a start you would be creating 5000 'mirror' `<textarea>` DOM elements, and 5000 `$scope.watch`, browsers simply won't cope with this.

`ng-repeat` performance is a real issue with AngularJS due to dirty checking, this is solved by Angular (2+), but that is not much help for your issue. Even 20 secs I would suggest is not acceptable performance. My recommendation would be to look at paginating your list.

Hope that helps, a bit!
